version: '3.9'

services:
  app:
    image: node:18
    working_dir: /usr/src/app
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - PORT=3000
